# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jacky\OneDrive\Documents\SlateInPost\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets

PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

class Ui_SlateInPost(object):
    def setupUi(self, SlateInPost):
        self.data = {}
        self.files = []
        self.info = []
        self.outputFile = None
        self.savePath = "./"
        font = QtGui.QFont()
        font.setPointSize(8)
        SlateInPost.setObjectName("SlateInPost")
        SlateInPost.resize(549, 454)
        self.centralwidget = QtWidgets.QWidget(SlateInPost)
        self.centralwidget.setObjectName("centralwidget")
        self.importBtn = QtWidgets.QPushButton(self.centralwidget)
        self.importBtn.setGeometry(QtCore.QRect(190, 60, 151, 51))
        self.importBtn.setObjectName("importBtn")
        self.importBtn.setFont(font)
        self.outputBtn = QtWidgets.QPushButton(self.centralwidget)
        self.outputBtn.setGeometry(QtCore.QRect(210, 180, 111, 31))
        self.outputBtn.setObjectName("outputBtn")
        self.outputBtn.setFont(font)
        self.stepOne = QtWidgets.QLabel(self.centralwidget)
        self.stepOne.setGeometry(QtCore.QRect(60, 30, 201, 16))
        self.stepOne.setObjectName("stepOne")
        self.stepOne.setFont(font)
        self.stepTwo = QtWidgets.QLabel(self.centralwidget)
        self.stepTwo.setGeometry(QtCore.QRect(60, 130, 291, 16))
        self.stepTwo.setObjectName("stepTwo")
        self.stepTwo.setFont(font)
        self.stepTwo_1 = QtWidgets.QLabel(self.centralwidget)
        self.stepTwo_1.setGeometry(QtCore.QRect(60, 150, 431, 16))
        self.stepTwo_1.setObjectName("stepTwo_1")
        self.stepTwo_1.setFont(font)
        self.stepThree = QtWidgets.QLabel(self.centralwidget)
        self.stepThree.setGeometry(QtCore.QRect(60, 220, 111, 16))
        self.stepThree.setObjectName("stepThree")
        self.stepThree.setFont(font)
        self.similaritySlider = QtWidgets.QSlider(self.centralwidget)
        self.similaritySlider.setGeometry(QtCore.QRect(60, 250, 160, 16))
        self.similaritySlider.setOrientation(QtCore.Qt.Horizontal)
        self.similaritySlider.setMinimum(30)
        self.similaritySlider.setMaximum(100)
        self.similaritySlider.setObjectName("similaritySlider")
        self.similarityLabel = QtWidgets.QLabel(self.centralwidget)
        self.similarityLabel.setGeometry(QtCore.QRect(90, 270, 91, 20))
        self.similarityLabel.setObjectName("similarityLabel")
        self.similarityLabel.setFont(font)
        self.deleteWAV = QtWidgets.QCheckBox(self.centralwidget)
        self.deleteWAV.setGeometry(QtCore.QRect(60, 320, 300, 18))
        self.deleteWAV.setObjectName("deleteWAV")
        self.deleteWAV.setFont(font)
        self.convertForMe = QtWidgets.QCheckBox(self.centralwidget)
        self.convertForMe.setGeometry(QtCore.QRect(60, 300, 300, 18))
        self.convertForMe.setObjectName("convertForMe")
        self.convertForMe.setText("Convert my media files for me (ffmpeg required).")
        self.convertForMe.setFont(font)
        self.speechAPIcombo = QtWidgets.QComboBox(self.centralwidget)
        self.speechAPIcombo.setGeometry(QtCore.QRect(320, 250, 151, 22))
        self.speechAPIcombo.setObjectName("speechAPIcombo")
        self.speechAPIcombo.setFont(font)
        self.speechAPIcombo.addItem("Google Speech Recognition")
        self.speechAPIcombo.addItem("Wit.ai")
        self.speechAPIcombo.addItem("Bing")
        self.speechAPIcombo.addItem("Houndify")
        self.speechAPIcombo.addItem("IBM")
        self.speechAPIlbl = QtWidgets.QLabel(self.centralwidget)
        self.speechAPIlbl.setGeometry(QtCore.QRect(320, 270, 161, 20))
        self.speechAPIlbl.setObjectName("speechAPIlbl")
        self.speechAPIlbl.setFont(font)
        self.actionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.actionBtn.setGeometry(QtCore.QRect(200, 385, 141, 41))
        self.actionBtn.setObjectName("actionBtn")
        fontB = QtGui.QFont()
        fontB.setBold(True)
        fontB.setItalic(False)
        fontB.setWeight(75)
        fontB.setPointSize(8)
        self.actionBtn.setFont(fontB)
        SlateInPost.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SlateInPost)
        self.statusbar.setObjectName("statusbar")
        SlateInPost.setStatusBar(self.statusbar)

        self.retranslateUi(SlateInPost)
        QtCore.QMetaObject.connectSlotsByName(SlateInPost)


    def retranslateUi(self, SlateInPost):
        _translate = QtCore.QCoreApplication.translate
        SlateInPost.setWindowTitle(_translate("SlateInPost", "SlateInPost"))
        self.importBtn.setText(_translate("SlateInPost", "Import Media Files"))
        self.outputBtn.setText(_translate("SlateInPost", "Save output to..."))
        self.stepOne.setText(_translate("SlateInPost", "Step 1: select media files for syncing"))
        self.stepTwo.setText(_translate("SlateInPost", "Step 2: select output location. The output will be a .txt file."))
        self.stepTwo_1.setText(_translate("SlateInPost", "SlateInPost can also convert all your media files to .wav and save them to this folder."))
        self.stepThree.setText(_translate("SlateInPost", "Step 3: sync settings"))
        self.similarityLabel.setText(_translate("SlateInPost", "Similarity: " + str(self.similaritySlider.value()) + "%"))
        self.deleteWAV.setText(_translate("SlateInPost", "Delete created .wav files"))
        self.speechAPIlbl.setText(_translate("SlateInPost", "Speech recognition engine/API "))
        self.actionBtn.setText(_translate("SlateInPost", "Action!"))

